### ISSUE TITLE
Encrypted siteini 

### ISSUE THREAD

**Issue by Zero-Addon** [harrygg/xmltv-tools#10]
Hi!
I'm having problem with encrypted siteini's, it looks like is not compatible with that type of siteini.
all other siteini are working but with encrypted one, show this error:
`[ERROR] 1.1 | MOVISTARPLUS.ES | No XML programms found for channel Discovery Max with id 'DiscoveryMax.es' found in EPG!`

**Comment by tiagomiguelferreira** [comment]
Hi @Zero-Addon, having the same problem, from what i check in the code, is not a very difficult task to add the "decryptkey" property to the config file. 
Taking into account that the program is so well written and, nobody works for free, i think we could give some sort of donation to the author in order to try keeping wgmulti updated with webgrab++, for features like this.

**Comment by harrygg** [comment]
It's not as easy as I thought initially as wgmulti does not simply copy the config but parses it (for better or worse). I will try to implement it in the upcoming weeks.

**Comment by harrygg** [comment]
Fixed in latest binary
